# Generated by Django 4.0.3 on 2022-05-07 15:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Ustozllar royxati',
                'verbose_name_plural': 'Ustozlar',
            },
        ),
        migrations.CreateModel(
            name='Lessons',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lesson_name', models.CharField(max_length=400, verbose_name='Dars nomi')),
                ('video_file', models.FileField(upload_to='')),
                ('image', models.ImageField(upload_to='')),
                ('description', models.TextField(verbose_name='Dars haqida qisqacha')),
                ('quentity', models.IntegerField(default=0)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('teacher', models.ForeignKey(help_text='Dars ustozi', on_delete=django.db.models.deletion.CASCADE, to='teachers.teacher', verbose_name='Dars ustozi')),
            ],
            options={
                'verbose_name': 'On-line dars',
                'verbose_name_plural': 'On-line darslar',
            },
        ),
    ]
